modLoader = "javafml" #mandatory
loaderVersion = "[36,)"
license = "All rights reserved"
issueTrackerURL = "https://github.com/RobertSkalko/Balance-of-Exile/issues"
[[mods]]
modId = "anti_mob_farm"
version = "1.3.3"
displayName = "Anti Mob Farm"
#updateJSONURL="https://change.me.example.invalid/updates.json"
#displayURL="https://legacy.curseforge.com/minecraft/mc-mods/anti-mob-cheese"
logoFile = "icon.png"
credits = ""
authors = "mcrobertx22"
description = '''
Makes automatic mob farming very inefficient due to overkill chunk penalty!
'''
[[dependencies.anti_mob_farm]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.anti_mob_farm]]
modId = "library_of_exile"
mandatory = true
versionRange = "[0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.anti_mob_farm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
