modLoader = "javafml" #mandatory
loaderVersion = "[36,)"
license = "All rights reserved"
issueTrackerURL = "${mod_issues_link}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_display_name}"
displayURL="${mod_website_link}"
logoFile = "icon.png"
credits = ""
authors = "mcrobertx22"
description = '''
Makes automatic mob farming very inefficient due to overkill chunk penalty!
'''
[[dependencies.anti_mob_farm]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.anti_mob_farm]]
modId = "library_of_exile"
mandatory = true
versionRange = "[1.4.1,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.anti_mob_farm]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"
